### ISSUE TITLE
Unable to send in compiler flags

### ISSUE THREAD

**Issue by adamnovak** [Kmer-File-Format/kff-cpp-api#16]
The CMake file sets `CMAKE_CXX_FLAGS` with a `set()`, which can't be overridden on the `cmake` command line with a `-D`. So it's not possible to pass additional compiler flags (such as `-fPIC` for using this library as a dependency of a shared library) into the build.

https://github.com/Kmer-File-Format/kff-cpp-api/blame/c490ddb603074b0c4c3efecc3a3c8506b059ffaf/CMakeLists.txt#L15

**Comment by yoann-dufresne** [comment]
Hi,

Thanks from reaching us. [I updated the CMakeLists.txt](https://github.com/Kmer-File-Format/kff-cpp-api/commit/2a5ede6a11bde054f5304e95b69252e9cdfb7e0b) so you can now pass these flags from the command line.
Do not hesitate if you have other questions.

Yoann
