### ISSUE TITLE
'max' global variable

### ISSUE THREAD

**Issue by rchikhi** [Kmer-File-Format/kff-cpp-api#2]
when 'max' variable isn't set, kff throws `throw "Impossible to read the raw section due to missing max variable";` but in the C++ API doc it's not clear what this variable does

**Comment by rchikhi** [comment]
ah! it's here https://github.com/Kmer-File-Format/kff-reference#section-raw-sequences

**Comment by yoann-dufresne** [comment]
Thanks for the question and the answer !
